documentation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('reports/', include('reports.urls')),
    path('test_lab_schedule/', include('test_lab_schedule.urls')),
    path('admin/', admin.site.urls),
]

reports/urls.py
from django.urls import path

from . import views

app_name = 'reports'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('bike_list/', views.BomBikeView.as_view(), name='bike_list'),
    path('bike_report/<int:pid>/', views.bikereport, name='bikereport'),
    path('part_list/', views.PartListView.as_view(), name='part_view'),
    path('testreportpart/<int:pk>/', views.TrpDetailView.as_view(), name='trp_detail'),
    path('testreportcombo/<int:pk>/', views.TrcDetailView.as_view(), name='trc_detail'),
    path('part/<int:pk>/', views.PartDetailView.as_view(), name='part_detail'),
    path('part_search/', views.part_search, name='part_search'),
    path('bike_search/', views.bike_search, name='bike_search'),
    path('csv_upload/', views.csv_upload, name='csv_upload'),
    path('failure/', views.failure, name='failure'),
    path('readiness/', views.bike_readiness, name='bike_readiness'),
]

reports/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from datetime import date

class CsvUploadForm(forms.Form):
    file_type = forms.ChoiceField(
        choices=[
            ("bikebom", "Bike BOM"),
            ("parts", "Parts"),
            ("test_report_part", "Test Report Part"),
            ("test_report_combo", "Test Report Combo"),
            ("pid", "PID"),
            ("bike_reports", "Bike Reports"),
            ("bike_report_toc", "Bike Report TOC")
        ],
        required=False,
    )
    attachment = forms.FileField(validators=[FileExtensionValidator(["csv"])], required=False)

class BikeSearchForm(forms.Form):
    QUARTERS = (
        ("1-12", "All"),
        ("1-3", "Q1"),
        ("4-6", "Q2"),
        ("7-9", "Q3"),
        ("10-12", "Q4"),
    )
    ATTRS = {
        'class': 'form-check-inline',
        'style': 'margin-right: 0px; margin-left: 5px;'
    }
    this_year = date.today().year + 1
    bike_model = forms.CharField(max_length=50, required=False)
    production_year = forms.IntegerField(localize=False, required=False, initial=this_year)
    quarter = forms.ChoiceField(
        choices=QUARTERS,
        widget=forms.RadioSelect(attrs=ATTRS),
        required=False,
        initial=QUARTERS[0][0]
    )

reports/views.py
from datetime import date

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView

from .models import BikeReport, BomBike, Part, TestReportCombo, TestReportPart
from .importers import Csv_Importer
from .forms import CsvUploadForm, BikeSearchForm

# Create your views here.
def home(request):
    return render(request, 'reports/home.html')

class BomBikeView(ListView):
    this_year = date.today().year
    next_year = this_year + 1
    families = []
    bikes = []

    model = BomBike
    # Obtain the bikes for this calendar year (from Jan 1 to Dec 31)
    queryset = BomBike.objects.filter(production_date__gte=str(this_year)+'-01-01').filter(production_date__lt=str(next_year)+'-01-01').order_by('production_date')
    for bike in queryset:
        if bike.model not in families:
            bikes.append(bike)
            families.append(bike.model)
    queryset = bikes
    context_object_name = 'bikes'
    template_name = 'reports/bike_list.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the parts

        return context

class PartListView(ListView):
    template_name = 'reports/part_list.html'

class PartDetailView(DetailView):
    model = Part
    # generic views uses template name <app name>/<model name>_detail.html
    template_name = 'reports/part_detail.html'

class TrpDetailView(DetailView):
    model = TestReportPart
    template_name = 'reports/trp_detail.html'

class TrcDetailView(DetailView):
    model = TestReportCombo
    template_name = 'reports/trc_detail.html'

def bikereport(request, pid):
    bikereport = BikeReport.objects.get(pid=pid)
    bikes = BomBike.objects.filter(report=bikereport)
    return render(request, 'reports/bike_report.html', {
        'bikes':bikes, 
        'bikereport':bikereport, 
        }
    )

def bike_search(request):
    if request.method == "POST":
        form = BikeSearchForm(request.POST)
        if form.is_valid():
            model_year = form.cleaned_data['model_year']
            search_term = form.cleaned_data['search']
            if model_year:
                results = BikeReport.objects.filter(description__contains=model_year).filter(description__contains=search_term)
            else:
                results = BikeReport.objects.filter(description__contains=search_term)

            form = BikeSearchForm()
            return render(request, 'reports/bike_search.html', {'form':form, 'results':results})
    else:
        form = BikeSearchForm()
    
    return render(request, 'reports/bike_search.html', {'form':form})

def part_search(request):
    if request.method == "POST":
        parts = Part.objects.filter(description__contains = request.POST['description'])
        if not parts:
            # Redisplay the form
            return render(request, 'reports/part_search.html', {
                'error_message': "Could not find part."
            })
        else:
            # Always return an HttpResponseRedirect after succesfully dealing with POST data.
            # This prevents data from being posted twice if a user hits the Back button.
            return render(request, 'reports/part_search.html', {'parts':parts})
    else:
        return render(request, 'reports/part_search.html')

def csv_upload(request):

    if request.method == "POST":
        form = CsvUploadForm(request.POST, request.FILES)
        # Form is already checking that the uploaded file is csv. Refer
        # to validators argument in the FileField of csv upload form in forms.py
        if form.is_valid():
            importer = Csv_Importer(request.FILES['attachment'])
            # Read the file and get the headers
            try:
                importer.read_file()
            except:
                return HttpResponseRedirect(reverse('reports:failure'))
            # Determine if it's a part, trp, trc, etc.
            importer.determine_type()
            if importer.csv_type == "unknown":
                return HttpResponseRedirect(reverse('reports:failure'))
            # Import the data
            importer.import_all()
            return render(request, 'reports/csv_upload.html')
        else:
            return HttpResponseRedirect(reverse('reports:failure'))
    else:
        form = CsvUploadForm()
    return render(request, 'reports/csv_upload.html')

def failure(request):
    return render(request, 'reports/failure.html')

def success(request):
    return render(request, 'reports/success.html')

def bike_readiness(request):
    # get the current year
    next_year = date.today().year + 1

    # Processing the form data for a POST request
    if request.method == "POST":
        # create a form instance and populate it with data from the request
        form = BikeSearchForm(request.POST)
        date1 = date(year=next_year, month=1, day=1)
        date2 = date(year=next_year, month=12, day=31)
        bikes = []
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            bike_model = form.cleaned_data['bike_model']
            production_year = form.cleaned_data['production_year']
            quarter = form.cleaned_data['quarter']
            
            if production_year and quarter:
                date1 = date(year=production_year, month=int(quarter.split("-")[0]), day=1)
                date2 = date(year=production_year, month=int(quarter.split("-")[1]), day=1)

            elif production_year:
                date1 = date(year=production_year, month=1, day=1)
                date2 = date(year=production_year, month=12, day=1)

            if bike_model:
                bikes = BomBike.objects.filter(
                    model__icontains=bike_model).filter(
                        production_date__gte=date1).filter(production_date__lte=date2).order_by(
                            'production_date'
                        )
            else:
                bikes = BomBike.objects.filter(
                        production_date__gte=date1).filter(production_date__lte=date2).order_by(
                            'production_date'
                        )

    # if a GET (or any other method) we'll create a blank form
    else:
        form = BikeSearchForm()
        bikes = []
    
    return render(request, 'reports/bike_readiness.html',
            {
                "bikes":bikes,
                "form":form
            }
        )

reports/templates/reports/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'reports/styles.css' %}">
</head>


<body>

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'reports:home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'reports:bike_list' %}">Bike List</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'reports:csv_upload' %}">Csv Upload</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'reports:bike_readiness' %}">Bike Readiness Report</a></li>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Bike search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </ul>
    </nav>
</div>

<br>

{% block content %}
{% endblock %}

</body>
</html>

reports/templates/reports/bike_list.html
{% extends 'reports/base.html' %}

{% block content %}

    <h1>Bike List</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Production Date</th>
                <th>PID</th>
                <th>Bike Family</th>
            </tr>
        </thead>
        <tbody>
            {% for bike in bikes %}
            <tr>
                <td>{{bike.production_date}}</td>
                <td><a href="{% url 'reports:bikereport' bike.report.pid %}">{{bike.report.pid}}</a></td>
                <td>{{bike.model}}</td>
            </tr>
            {% endfor %}
        </tbody>
    
    </table>


{% endblock %}

reports/templates/reports/bike_readiness.html
{% extends 'reports/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h1>Bike Readiness Report</h1>
    </div>

    <div class="row">
        <form action="{% url 'reports:bike_readiness' %}" method="post">
            {% csrf_token %}
                <div>
                    {{form.bike_model.label_tag}}
                    {{form.bike_model}}
                </div>
                <div>
                    {{form.production_year.label_tag}}
                    {{form.production_year}}
                </div>
                <div>
                    {{form.quarter}}
                    <input type="submit" value="Search">
                </div>
        </form>
    </div>

    <div class="row">
        <table class="table table-condensed table-bordered">
            <thead>
                <tr>
                    <th>Bike Model</th>
                    <th>Prod Date</th>
                    <th>Frame</th>
                    <th>Fork</th>
                    <th>HbStem</th>
                    <th>Sdlstp</th>
                    <th>BBCrst</th>
                    <th>Full Bike Cert?</th>
                </tr>
            </thead>
            <tbody>
                {% for bike in bikes %}
                <tr>
                    <td>{{bike}}</td>
                    <td>{{bike.production_date}}</td>

                    <td class="{{bike.frame.has_report.lifecycle}}">
                        {% for report in bike.frame.has_report.reports %}
                        <a href="{% url 'reports:part_detail' bike.frame.id %}">{{report.agile_number}}</a>
                        {% endfor %}
                    </td>

                    <td class="{{bike.fork.has_report.lifecycle}}">
                        {% for report in bike.fork.has_report.reports %}
                            {{report.agile_number}}
                        {% endfor %}
                    </td>

                    <td class="{{bike.has_hbstem_trc.lifecycle}}">
                        {% for report in bike.has_hbstem_trc.reports %}
                            {{report.agile_number}}
                        {% endfor %}
                    </td>

                    <td class="{{bike.has_sdlstp_trc.lifecycle}}">
                        {% for report in bike.has_sdlstp_trc.reports %}
                            {{report.agile_number}}
                        {% endfor %}
                    </td>

                    <td class="{{bike.has_bbc_trc.lifecycle}}">
                        {% for report in bike.has_bbc_trc.reports %}
                            {{report.agile_number}}
                        {% endfor %}
                    </td>
                    
                    <td>{{bike.report.has_attachment}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>


{% endblock %}

reports/templates/reports/bike_report.html
{% extends 'reports/base.html' %}


{% block content %}

<div class="container">
    <h1>{{bikereport.description}}</h1>
    <table class="table">
        <tr>
            <th>Bike Report Agile no.</th>
            <td>{{bikereport.agile_number}}</td>
        </tr>
        <tr>
            <th>Production Date</th>
            <td>{{bikereport.first_prod_date}}</td>
        </tr>
        <tr>
            <th>MPL Product ID</th>
            <td>{{bikereport.pid}}</td>
        </tr>
        <tr>
            <th>Assembler reports in Agile</th>
            <td>{{bikereport.has_attachment}}</td>
        </tr>
        <tr>
            <th>Is Ebike</th>
            <td>{{bikereport.ebike}}</td>
        </tr>
    </table>
    
</div>

<br>

<div class="container">
    {% for bike in bikes %}
    <h2>{{bike.size}}</h2>
        <table class="table table-bordered table-sm">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>Part Info</th>
                    <th>Report</th>
                    <th>In Agile Bike Report</th>
                </tr>
            </thead>
    
            <tbody>
                <tr>
                    <th>Frame</th>
                    <td><a href="{% url 'reports:part_detail' bike.frame.id %}">{{bike.frame}}</a></td>
                    {% with reports=bike.frame.get_reports %}
                        <td>{% for report in reports %}
                                {{report}}&nbsp;
                            {% endfor %}
                        </td>

                        {% for report in reports %}

                        {% if report in bikereport.get_trps %}
                        <td>Yes</td>
                        {% else %}
                        <td>No</td>
                        {% endif %}

                        {% endfor %} 
                    {% endwith %}
                </tr>
        
                <tr>
                    <th>Fork</th>
                    <td><a href="{% url 'reports:part_detail' bike.fork.id %}">{{ bike.fork }}</a></td>
                    {% with reports=bike.fork.get_reports %}
                        <td>{% for report in reports %}
                                {{report}}&nbsp;
                            {% endfor %}
                        </td>

                        {% for report in reports %}

                        {% if report in bikereport.get_trps %}
                        <td>Yes</td>
                        {% else %}
                        <td>No</td>
                        {% endif %}

                        {% endfor %} 
                    {% endwith %}
                </tr>
                <!-- STEERING -->
                <tr>
                    <!--HEADER-->
                    <th rowspan="2">Steering</th>
                    <!-- PART INFO -->
                    <!-- HANDLEBAR-->
                    <td><a href="{% url 'reports:part_detail' bike.handlebar.id %}">{{ bike.handlebar }}</a></td>
                    <!-- COMBO REPORTS -->
                    {% with reports=bike.get_hbstem_reports %}
                    <td rowspan="2">
                        {% for report in reports %}
                            {{report}}&nbsp;
                        {% endfor %}
                    </td>
                    <!-- Checking if the reports have been added to the Product Model page in Agile -->
                    {% for report in reports %}
                        {% if report in bikereport.get_trcs %}
                        <td rowspan="2">True</td>
                        {% else %}
                        <td rowspan="2">False</td>
                        {% endif %}
                    {% endfor %} 
                    {% endwith %}
                </tr>
                <!-- STEM -->
                <tr>
                    <td><a href="{% url 'reports:part_detail' bike.stem.id %}">{{ bike.stem }}</a></td>
                </tr>
                <!-- SADDLE AND SEATPOST -->
                <tr>
                    <!--HEADER-->
                    <th rowspan="2">Saddle Seatpost
                    </th>
                    <!-- PART INFO -->
                    <!-- SADDLE -->
                    <td><a href="{% url 'reports:part_detail' bike.saddle.id %}">{{ bike.saddle }}</a></td>
                    <!-- COMBO REPORTS -->
                    {% with reports=bike.get_sdlstp_reports %}
                    <td rowspan="2">
                        {% for report in reports %}
                            {{report}}&nbsp;
                        {% endfor %}
                    </td>
                    <!-- Checking if the reports have been added to the Product Model page in Agile -->
                    {% for report in reports %}
                        {% if report in bikereport.get_trcs %}
                        <td rowspan="2">True</td>
                        {% else %}
                        <td rowspan="2">False</td>
                        {% endif %}
                    {% endfor %} 
                    {% endwith %}
                </tr>
                <!-- SEAT POST -->
                <tr>
                    <td><a href="{% url 'reports:part_detail' bike.seatpost.id %}">{{ bike.seatpost }}</a></td>
                </tr>

                <!-- BB AND CRANKSET -->
                <tr>
                    <!--HEADER-->
                    <th rowspan="2">Drivetrain</th>
                    <!-- PART INFO -->
                    <!-- BB-->
                    <td><a href="{% url 'reports:part_detail' bike.bb.id %}">{{ bike.bb }}</a></td>
                    <!-- COMBO REPORTS -->
                    {% with reports=bike.get_bbc_reports %}
                    <td rowspan="2">
                        {% for report in reports %}
                            {{report}}&nbsp;
                        {% endfor %}
                    </td>
                    <!-- Checking if the reports have been added to the Product Model page in Agile -->
                    {% for report in reports %}
                        {% if report in bikereport.get_trcs %}
                        <td rowspan="2">True</td>
                        {% else %}
                        <td rowspan="2">False</td>
                        {% endif %}
                    {% endfor %} 
                    {% endwith %}
                </tr>
                <!-- CRANKSET -->
                <tr>
                    <td><a href="{% url 'reports:part_detail' bike.cs.id %}">{{ bike.cs }}</a></td>
                </tr>
        
            </tbody>
        </table>
        <br>
    {% endfor %}
</div>



{% endblock %}

reports/templates/reports/bike_search.html
{% extends "reports/base.html" %}

{% block title %}Bike Search{% endblock %}

{% block content %}

<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Search">
    </form>
</div>

<div>
    {% if results %}
    <h1>Search Results</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">PID</td>
                <th scope="col">Bike Report Agile Number</td>
                <th scope="col">Description</td>
            </tr>
        </thead>
        <tbody>
        {% for result in results %}
        <tr>
            <td>{{result.pid}}</td>
            <td><a href="{% url 'reports:bikereport' result.id %}"><p>{{result.agile_number}}</p></a></td>
            <td>{{result.description}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock %}

reports/templates/reports/csv_upload.html
{% extends "reports/base.html" %}

{% block title %}CSV Upload{% endblock %}

{% block content %}
<form action="{% url 'reports:csv_upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Upload CSV file</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <label for="attachment">Select a file:</label>
        <input type="file" name="attachment"><br>
    </fieldset>
    <input type="submit" value="Upload">
</form>

{% endblock %}

reports/templates/reports/failure.html
<h1>Failure</h1>

{{ message }}

reports/templates/reports/home.html
{% extends "reports/base.html" %}

{% block content %}
<h1>Home</h1>
{% endblock %}

reports/templates/reports/part_detail.html
{% extends 'reports/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <h3>{{part.description}}</h3>

        <table class="table">
            <tr>
                <th>Agile number</th>
                <td> {{part.agile_number}} </td>
            </tr>
            <tr>
                <th>Lifecycle</th>
                <td>{{ part.lifecycle }}</td>
            </tr>
            <tr>
                <th>Other names</th>
                <td>
                    {% for name in part.get_names %}
                        {{ name }} &nbsp;
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>TRPs used in</th>
                <td>
                    {% if part.get_reports %}
                    <div class="list-group"></div>
                        {% for report in part.get_reports %}
                        <a href="{% url 'reports:trp_detail' report.pk %}" class="list-group-item">{{ report }}</a>
                    {% endfor %}
                    </div>
        
                    {% else %}
                        No Reports
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>TRCs used in</th>
                <td>
                    {% if part.get_trcs %}
                    <div class="list-group">
                        {% for report in part.get_trcs %}
                        <a href="{% url 'reports:trc_detail' report.pk %}" class="list-group-item">{{ report }}</a>
                    {% endfor %}
                    </div>
        
                    {% else %}
                        No Reports
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Bikes used in</th>
                <td>
                    <div class="list-group">
                        {% for bike in part.get_bikes %}
                        <a href="{% url 'reports:bikereport' bike.report.pid %}" class="list-group-item">{{bike.get_prod_year}} {{ bike }}</a>
                        {% endfor %}
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>



{% endblock %}

reports/templates/reports/part_search.html
<form action="{% url 'reports:part_search' %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>Search part</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <label for="description">Description</label>
    <input type="text" name="description"><br>
</fieldset>
<input type="submit" value="Search">
</form>

{% if parts %}
    <h1>Search Results:</h1>
    <ul>
    {% for part in parts %}
        <li><a href="{% url 'reports:part_detail' part.pk %}">{{ part.description }}</a></li>
    {% endfor %}
    </ul>
{% endif %}

reports/templates/reports/success.html
<h1>Upload successful</h1>

reports/templates/reports/trc_detail.html
<h1>{{ testreportcombo }}</h1>
<h2>Lifecycle</h2>
<ul>
    <li>{{ testreportcombo.lifecycle }}</li>
</ul>
<h2>Contents</h2>
<ul>
    {% for trp in testreportcombo.get_contents.trps %}
        <li><a href="{% url 'reports:trp_detail' trp.pk %}">{{ trp }}</a></li>
    {% endfor %}
    {% for part in testreportcombo.get_contents.parts %}
    <li><a href="{% url 'reports:part_detail' part.pk %}">{{ part }}</a></li>
{% endfor %}
</ul>

reports/templates/reports/trp_detail.html
{% extends 'reports/base.html' %}

{% block content %}

<h1>{{ testreportpart }}</h1>
<h2>Lifecycle</h2>
<ul>
    <li>{{ testreportpart.lifecycle }}</li>
</ul>
<h2>Contents</h2>
<ul>
    {% for part in testreportpart.get_contents %}
        <li><a href="{% url 'reports:part_detail' part.pk %}">{{ part }}</a></li>
    {% endfor %}
</ul>
<h2>TRCs that use this report</h2>
<ul>
    {% for trc in testreportpart.get_trcs %}
        <li><a href="{% url 'reports:trc_detail' trc.pk %}">{{ trc }}</a></li>
    {% endfor %}
</ul>

{% endblock %}