documentation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('reports/', include('reports.urls')),
    path('test_lab_schedule/', include('test_lab_schedule.urls')),
    path('admin/', admin.site.urls),
]

reports/urls.py
from django.urls import path

from . import views

app_name = 'reports'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('bike_list/', views.BomBikeView.as_view(), name='bike_list'),
    path('bike_report/<int:pid>/', views.bikereport, name='bikereport'),
    path('part_list/', views.PartListView.as_view(), name='part_view'),
    path('testreportpart/<int:pk>/', views.TrpDetailView.as_view(), name='trp_detail'),
    path('testreportcombo/<int:pk>/', views.TrcDetailView.as_view(), name='trc_detail'),
    path('part/<int:pk>/', views.PartDetailView.as_view(), name='part_detail'),
    path('part_search/', views.part_search, name='part_search'),
    path('bike_search/', views.bike_search, name='bike_search'),
    path('csv_upload/', views.csv_upload, name='csv_upload'),
    path('failure/', views.failure, name='failure'),
    path('readiness/', views.bike_readiness, name='bike_readiness'),
]

test_lab_schedule/urls.py
from django.urls import path, re_path
from django.contrib import admin

from . import views

app_name = 'test_lab_schedule'
urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('test/add/', views.add_test, name='add_test'),
    path('test/add/navbar', views.add_test_navbar, name='add_test_navbar'),
    path('test/edit/', views.edit_test, name='edit_test'),
    re_path(r'^test/edit/(?P<pk>\w+)/$', views.edit_test),
    path('test/<int:pk>', views.TestView.as_view(), name='test'),
    path('add_sample', views.addSample, name='add_sample'),
    path('test/<int:pk>/edit', views.edit_test, name='edit_test'),
    re_path(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    path('week/', views.weekview, name='week'),
    re_path(r'^week/(?P<filter>\w+)/$', views.weekview, name='filterweek'),
    path('tests/', views.test_list, name='test_list'),
    re_path(r'^tests/(?P<filter>\w+)/$', views.test_list, name='filtertestlist')
]

test_lab_schedule/models.py
from datetime import timedelta, date
from django.db import models
from django.core.exceptions import ValidationError

def is_technician(value):
    person = People.objects.get(pk=value)
    print(person.role)
    # Will reject people that are not technicians
    if person.role != 'TC':
        raise ValidationError(
            ('%(value)s is not a technician'),
            params={'value':value}
        )

class LabTestInfo(models.Model):
    test_full_name = models.CharField(max_length=255)
    test_acronym = models.CharField(max_length=32)
    standard = models.CharField(max_length=255, blank=True)
    work_instruction = models.CharField(max_length=10, blank=True)
    report_form = models.CharField(max_length=10, blank=True)
    test_duration_in_days = models.IntegerField()

    def __str__(self):
        return self.test_acronym

class Machine(models.Model):
    name = models.CharField(max_length=2, blank=False, null=False)
    capable_tests = models.ManyToManyField(LabTestInfo, blank=True)
    is_online = models.BooleanField()

    def __str__(self):
        return self.name

class People(models.Model):
    TECHNICIAN = 'TC'
    STAKEHOLDER = 'SH'
    DEVELOPER = 'DV'
    COMPLIANCE = 'CP'
    DESIGN_ENGINEER = 'DE'

    ROLES = [
        (TECHNICIAN, 'Technician'),
        (STAKEHOLDER, 'Stakeholder'),
        (DEVELOPER, 'Developer'),
        (COMPLIANCE, 'Compliance'),
        (DESIGN_ENGINEER, 'Design Engineer')
    ]
    name = models.CharField(max_length=255)
    email = models.EmailField(default="morban@specialized.com")
    role = models.CharField(max_length=255, choices=ROLES)

    def __str__(self):
        return self.name

class Bike(models.Model):
    model_year = models.IntegerField()
    bike_model = models.CharField(max_length=255)

    def __str__(self):
        return 'MY' + str(self.model_year) + ' ' + self.bike_model

class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    stakeholders = models.ManyToManyField(People)

    def __str__(self):
        return self.name

class Sample(models.Model):
    bike_model = models.ManyToManyField(Bike)
    part1 = models.CharField(max_length=255)
    part2 = models.CharField(max_length=255, blank=True, default='')
    part1_dimensions = models.CharField(max_length=255, blank=True)
    part2_dimensions = models.CharField(max_length=255, blank=True)
    part1_agile = models.CharField(max_length=10)
    part2_agile = models.CharField(max_length=10, blank=True, null=True)
    part1_manu = models.CharField(max_length=255)
    part2_manu = models.CharField(max_length=255, blank=True, null=True)
    expected_completion_date = models.DateField(blank=True, null=True)
    reporter = models.ForeignKey(People, on_delete=models.PROTECT)
    project = models.ForeignKey(Project, on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        if self.part2:
            return self.part1 + ' / ' + self.part2
        else:
            return self.part1

class Test(models.Model):
    TEST_RESULTS = (
        ('QUEUE', 'Test Queue'),
        ('PASS', 'Meets Criteria'),
        ('FAIL', 'Does Not Meet Criteria'),
        ('RND', 'R&D Test Complete'),
        ('CANCEL', 'Cancelled'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)
    labtestinfo = models.ForeignKey(LabTestInfo, on_delete=models.PROTECT)
    result = models.CharField(max_length=255, choices=TEST_RESULTS, default=('QUEUE'))
    lims = models.CharField(max_length=10)
    start_date = models.DateField()
    end_date = models.DateField()
    machine = models.ForeignKey(Machine, null=True, on_delete=models.PROTECT)
    technician = models.ForeignKey(People, null=True, on_delete=models.PROTECT, validators=[is_technician])

    def calculate_end_date(self):
        days = timedelta(days=self.labtestinfo.test_duration_in_days)
        return self.start_date + days

    def get_reporter(self):
        return self.sample.reporter

    def is_delayed(self):
        if self.result == 'QUEUE':
            if self.end_date > date.today():
                return True

    def __str__(self):
        return 'LIMS-' + self.lims + ' --- ' + self.labtestinfo.test_acronym +  ' --- MACHINE ' + self.machine.name

test_lab_schedule/forms.py
from django import forms
from .models import LabTestInfo, Machine, People
from .widget import DatePickerInput

tests = LabTestInfo.objects.all()
machines = Machine.objects.all()
technicians = People.objects.filter(role='TC')

TEST_RESULTS = (
        ('QUEUE', 'Test Queue'),
        ('PASS', 'Meets Criteria'),
        ('FAIL', 'Does Not Meet Criteria'),
        ('RND', 'R&D Test Complete'),
        ('CANCEL', 'Cancelled'),
    )

class TestForm(forms.Form):
    lims = forms.CharField()
    labtestinfo = forms.ModelChoiceField(queryset=tests ,label='Test')
    machine = forms.ModelChoiceField(queryset=machines)
    technician = forms.ModelChoiceField(queryset=technicians)
    start_date = forms.DateField(widget=DatePickerInput())
    end_date = forms.DateField(widget=DatePickerInput())

class EditTestForm(forms.Form):
    machine = forms.ModelChoiceField(queryset=machines)
    technician = forms.ModelChoiceField(queryset=technicians)
    start_date = forms.DateField(widget=DatePickerInput())
    end_date = forms.DateField(widget=DatePickerInput())
    result = forms.ChoiceField(choices=TEST_RESULTS)

test_lab_schedule/views.py
from datetime import date, timedelta
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.http import HttpResponse
from django.views import generic
from django.utils.safestring import mark_safe
from calendar import monthrange

from .models import People, Machine, Test
from .utils import Calendar, WeeklyCalendar
from .forms import TestForm, EditTestForm, TEST_RESULTS

# Create your views here.

def index(request):
    return render(request, 'test_lab_schedule/index.html')

class TestView(generic.DetailView):
    model = Test
    template_name = 'test_lab_schedule/test.html'

class CalendarView(generic.ListView):
    model = Test
    template_name = 'test_lab_schedule/calendar.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month',None))
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['header'] = 'Calendar'
        return context

def weekview(request, filter='machine'):
    template_name = 'test_lab_schedule/week.html'

    # use today's date for the calendar
    d = get_date(request.GET.get('week',None))

    # Instantiate our calendar class with today's year and date
    cal = WeeklyCalendar(d.year, d.month, d.day)

    # Get the dates for today's week in the calendar
    dates = cal.get_week()[1]

    return render(request, 'test_lab_schedule/week.html', {
        'prev_week':prev_week(d),
        'next_week':next_week(d),
        'today':this_week(d),
        'filter':filter,
        'dates':dates,
        'rows':[],
        'header':filter.capitalize()
    })

def test_list(request, filter):
    d = get_date(request.GET.get('week',None))
    cal = WeeklyCalendar(d.year, d.month, d.day)
    tests = cal.get_tests(filter)
    return render(request, "test_lab_schedule/test_list.html", {"tests":tests, 'filter':filter})

def add_test(request):
    if request.method == "POST":
        form = TestForm(request.POST)
        if form.is_valid():
            lims = form.cleaned_data['lims']
            labtestinfo = form.cleaned_data['labtestinfo']
            machine = form.cleaned_data['machine']
            technician = form.cleaned_data['technician']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            test = Test.objects.create(
                lims=lims,
                labtestinfo=labtestinfo,
                start_date=start_date,
                end_date=end_date,
                machine=machine,
                technician=technician
            )
            test.save()
            return HttpResponse(status=204, headers={'HX-Trigger':"testListChanged"}) # 204 is status code for no content
    else:
        form = TestForm()
    return render(request, 'test_lab_schedule/test_form.html', {
        'form':form,
        'add_or_edit':'Add',
    })

def add_test_navbar(request):
    if request.method == "POST":
        form = TestForm(request.POST)
        if form.is_valid():
            lims = form.cleaned_data['lims']
            labtestinfo = form.cleaned_data['labtestinfo']
            machine = form.cleaned_data['machine']
            technician = form.cleaned_data['technician']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            test = Test.objects.create(
                lims=lims,
                labtestinfo=labtestinfo,
                start_date=start_date,
                end_date=end_date,
                machine=machine,
                technician=technician
            )
            test.save()
            return redirect("test_lab_schedule:week")
    else:
        form = TestForm()
    return render(request, 'test_lab_schedule/test_form_navbar.html', {
        'form':form,
        'add_or_edit':'Add',
    })

def edit_test(request, pk):
    test = get_object_or_404(Test, pk=pk)
    if request.method == "POST":
        form = EditTestForm(request.POST)
        if form.is_valid():
            test.machine = form.cleaned_data['machine']
            test.technician = form.cleaned_data['technician']
            test.start_date = form.cleaned_data['start_date']
            test.end_date = form.cleaned_data['end_date']
            test.result = form.cleaned_data['result']
            test.save()
            return HttpResponse(status=204, headers={'HX-Trigger':"testListChanged"}) # 204 is status code for no content
    else:
        form = EditTestForm(data={
            'machine':test.machine,
            'technician':test.technician,
            'start_date':test.start_date,
            'end_date':test.end_date,
            'result':test.result
        })
    return render(request, 'test_lab_schedule/edit_test_form.html', {
        'form':form,
        'test':test,
        'add_or_edit':'Edit'
    })

def addSample(request):
    return render(request, 'test_lab_schdule/add_sample.html')

def get_date(req_day):
    if req_day and len(req_day.split('-'))==3:
        year, month, day = (int(x) for x in req_day.split('-'))
        return date(year, month, day)
    elif req_day and len(req_day.split('-'))==2:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, 1)
    return date.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def prev_week(today):
    date_one_week_ago = today - timedelta(days=7)
    week = 'week=' + str(date_one_week_ago.year) + '-' + str(date_one_week_ago.month) + '-' + str(date_one_week_ago.day)
    return week

def next_week(today):
    date_one_week_later = today + timedelta(days=7)
    week = 'week=' + str(date_one_week_later.year) + '-' + str(date_one_week_later.month) + '-' + str(date_one_week_later.day)
    return week

def this_week(today):
    week = 'week=' + str(today.year) + '-' + str(today.month) + '-' + str(today.day)
    return week

test_lab_schedule/templates/test_lab_schedule/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}

<!doctype html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'test_lab_schedule/styles.css' %}">
  
  <title>Test Lab Schedule</title>
</head>

<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'test_lab_schedule:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'test_lab_schedule:calendar' %}">Monthly Calendar</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Weekly Views
                    </a>
                    <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'test_lab_schedule:filterweek' filter='machine' %}">Machine</a></li>
                    <li><a class="dropdown-item" href="#">Technician</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'test_lab_schedule:add_test_navbar' %}">Add Test</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'test_lab_schedule:add_sample'%}">Add Sample</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/admin/">Admin</a>
                </li>
                </ul>
            </div>
        </div>
        </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 text-center">
        {% block header %}
        {% endblock %}
      </div>
    </div>

{% block content%}
{% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="https://unpkg.com/htmx.org@1.8.0"></script>
  <script src="{% static 'test_lab_schedule/dialog.js' %}"></script>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>


</body>

</html>

test_lab_schedule/templates/test_lab_schedule/base_no_navbar.html
<!-- cal/templates/cal/base.html -->

{% load static %}

<!doctype html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'test_lab_schedule/styles.css' %}">
  
  <title>Test Lab Schedule</title>
</head>

<body>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 text-center">
        {% block header %}
        {% endblock %}
      </div>
    </div>

{% block content%}
{% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="https://unpkg.com/htmx.org@1.8.0"></script>
  <script src="{% static 'test_lab_schedule/dialog.js' %}"></script>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>


</body>

</html>

test_lab_schedule/templates/test_lab_schedule/calendar.html
{% extends 'test_lab_schedule/base.html' %}

{% block header %}
<h1>Test Lab Schedule - {{header}} view</h1>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-4">
	  <a class="btn btn-info left" href="{% url 'test_lab_schedule:calendar' %}{{ filter }}?{{ prev_month }}"> Last Month </a>
	  <a class="btn btn-info left" href="{% url 'test_lab_schedule:calendar' %}{{ filter }}?{{ next_month }}"> Next Month </a>
	</div>
	<div class="col-md-8">
	  <button type="button" hx-get="{% url 'test_lab_schedule:add_test' %}" hx-target="#dialog" class="btn btn-primary right">
		Add Test 
	  </button>	
	</div>
</div>

<!-- Table -->
<div class="row">
	<div class="col-md-12">
		<table cellpadding="0" cellspacing="0" class="table table-striped table-bordered weeklytable calendar">
			{{ calendar }}
		</table>
	</div>
</div>


{% endblock %}

test_lab_schedule/templates/test_lab_schedule/edit_test_form.html
{% extends 'test_lab_schedule/base_no_navbar.html' %}

{% block content %}
<div class="container">
    <form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
      {% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title">{{add_or_edit}} Test</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" hx-post="{{ request.path }}">
          {% csrf_token %}
          <a href="https://jira.specialized.com/browse/LIMS-{{test.lims}}"><p>LIMS-{{test.lims}}</p></a>
          <p>{{test.labtestinfo}}</p>
          {{ form.as_p }}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger left">Delete</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Cancel
        </button>
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </form>
    </div>
{% endblock %}

test_lab_schedule/templates/test_lab_schedule/index.html
{% extends 'test_lab_schedule/base.html' %}

{% block header %}
<h1>Home</h1>
{% endblock%}

{% block content %}
<h3>Home, what should we place here?</h3>
{% endblock %}

test_lab_schedule/templates/test_lab_schedule/machine.html
{% extends 'test_lab_schedule/week.html' %}

test_lab_schedule/templates/test_lab_schedule/test_form.html
{% extends 'test_lab_schedule/base_no_navbar.html' %}

{% block content %}

<div class="container">
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title">{{add_or_edit}} Test</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form method="POST" hx-post="{{ request.path }}">
      {% csrf_token %}
      {{ form.as_p }}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">
      Cancel
    </button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>
</div>
{% endblock %}

test_lab_schedule/templates/test_lab_schedule/test_form_navbar.html
{% extends 'test_lab_schedule/base.html' %}

{% block content %}

<div class="container">
<form action="{% url 'test_lab_schedule:add_test_navbar' %}" method="post">
    {% csrf_token %}
    <h5 class="modal-title">Add Test</h5>
      {% csrf_token %}
      {{ form.as_p }}
    <button type="submit" class="btn btn-primary left">Save</button>
</form>
</div>
{% endblock %}

test_lab_schedule/templates/test_lab_schedule/test_list.html
{% for test in tests %}
<tr>
  {% if filter == 'machine' %}
  <td>{{test.object.name}}</td>
  {% endif %}
  {% for day in test.tests %}
  <td>
    {% for ticket in day %}
    <li>
      <button type="button" class="btn btn-outline-primary btn-sm {{ticket.result}}" hx-get="{% url 'test_lab_schedule:edit_test' %}{{ticket.pk}}" hx-target="#dialog">
        {{ticket.project}} -- 
        {{ticket.lims}} -- {{ticket.labtestinfo}} -- {{ticket.technician}}
      </button>
    </li>
    {% endfor %}
  </td>
  {% endfor %}
</tr>


{% endfor %}

test_lab_schedule/templates/test_lab_schedule/week.html
{% extends 'test_lab_schedule/base.html' %}

{% block header %}
<h1>Test Lab Schedule - {{header}} view</h1>
{% endblock %}

{% block content %}

  <!-- Next and previous week buttons -->
    <div class="row">
      <div class="col-md-4">
        <a class="btn btn-info left" href="{% url 'test_lab_schedule:week' %}{{ filter }}?{{ prev_week }}"> Last Week </a>
        <a class="btn btn-info left" href="{% url 'test_lab_schedule:week' %}{{ filter }}?{{ next_week }}"> Next Week </a>
      </div>
      <div class="col-md-8">
        <button type="button" hx-get="{% url 'test_lab_schedule:add_test' %}" hx-target="#dialog" class="btn btn-primary right">
          Add Test 
        </button>	
      </div>
    </div>

    <!-- Table -->
    <div class="row">
      <div class="col-md-12">
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered weeklytable">
          <thead>
            <tr>
              <th>{{column_header}}</th>
              {% for day, date in dates.items %}
              <th>{{day}} {{date}}</th>
              {% endfor %}
            </tr>
          </thead>
          <tbody hx-trigger="load, testListChanged from:body" hx-get="{% url 'test_lab_schedule:test_list' %}{{ filter }}?{{ today }}" hx-target="this">
          </tbody>
        </table>
      </div>
    </div>


    <!-- Modal content (the dialog box that pops up and disappears )-->

    <div id="modal" class="modal fade" tabindex="-1" role="dialog">
      <div id="dialog" class="modal-dialog" role="document" hx-target="this">
        <!-- Insert HTML here -->
      </div>
    </div>
  </div>

{% endblock %}

  